In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
import numpy as np
a=np.array([[1,2,1],[3,4,5],[5,6,9]])
print(a)

[[1 2 1]
 [3 4 5]
 [5 6 9]]


In [14]:
np.zeros([2,3],int)

array([[0, 0, 0],
       [0, 0, 0]])

In [48]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
 a=np.empty([4,4],int)
a.fill(11)
print(a)

[[11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]]


In [36]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
np.linspace(0,20,5,dtype=int)

array([ 0,  5, 10, 15, 20])

In [51]:
np.full([3,3],20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [52]:
import numpy as np
a=np.array([[1,2,1],[3,4,5],[5,6,9]])
a.ndim

2

In [53]:
import numpy as np
a=np.array([[1,2,1],[3,4,5],[5,6,9]])
a.shape

(3, 3)

In [78]:
import numpy as np
a=np.array([[1,2,1],[3,4,5],[5,6,9]])
print(a.dtype)
print(a)
b=a.astype(float)
print(b.dtype)
print(b)




int32
[[1 2 1]
 [3 4 5]
 [5 6 9]]
float64
[[1. 2. 1.]
 [3. 4. 5.]
 [5. 6. 9.]]


In [80]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)
a.reshape(2,3)

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
import numpy as np
a=np.array([[5,6,9],[1,2,1],[3,4,5]])
print(a)

a.sort(axis=0)
print(a)


[[5 6 9]
 [1 2 1]
 [3 4 5]]
[[1 2 1]
 [3 4 5]
 [5 6 9]]


In [104]:
import numpy as np
a=np.array([[1,2,1],[3,4,5],[5,6,9]])
print(a)
a.sort(axis=1)
print(a)

[[1 2 1]
 [3 4 5]
 [5 6 9]]
[[1 1 2]
 [3 4 5]
 [5 6 9]]


In [113]:
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])